name: Fetch Stock Snapshot

on:
  schedule:
    - cron: '*/20 9-20 * * 1-5'  # every 20 min 9–20 UTC, Mon–Fri
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install yfinance pandas

      - name: Run snapshot script
        run: python snapshot.py

      - name: Upload CSV artifact
        uses: actions/upload-artifact@v2
        with:
          name: stock_snapshot
          path: stock_snapshot.csv
